import type { OAuthPreset } from "@peach-pi/shared-types";

/** Custom URL scheme for OAuth deep-link callbacks. */
export const DEEP_LINK_SCHEME = "peachpi";
export const DEEP_LINK_REDIRECT = `${DEEP_LINK_SCHEME}://oauth/callback`;

/** Shared loopback redirect for providers that reject custom schemes. One
 *  fixed port: only one handshake runs at a time and the server closes after.
 *  Users register THIS exact URI in their provider OAuth app. */
export const LOOPBACK_REDIRECT = "http://localhost:8471/callback";

/**
 * Static connector catalog (Path B: plain provider OAuth + REST — pi has no
 * MCP, so connectors are used by agent tools via `connectors:resolve`).
 *
 * Each entry pre-fills the connect form: a tile click leaves only client_id
 * (+ secret where required) for the user. peach-pi bundles no client_ids yet,
 * so `clientId` is undefined — the user registers their own OAuth app at
 * `docsUrl` and pastes the credentials. The "Custom…" tile (BYO form) covers
 * anything not listed here.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * ENDPOINTS BELOW ARE FROM KNOWLEDGE, NOT LIVE-VERIFIED. Before relying on a
 * provider, confirm its authorize/token URLs + scopes against current docs and
 * edit the single entry. Adding a provider = append one object here (+ an
 * optional simple-icons slug); no other code changes needed.
 * ─────────────────────────────────────────────────────────────────────────
 */
export const OAUTH_PRESETS: OAuthPreset[] = [
  {
    provider: "notion",
    label: "Notion",
    icon: "notion",
    authorizeUrl: "https://api.notion.com/v1/oauth/authorize",
    tokenUrl: "https://api.notion.com/v1/oauth/token",
    apiBaseUrl: "https://api.notion.com/v1",
    docsUrl: "https://www.notion.so/my-integrations",
    scopes: [],
    usePkce: false,
    useBasicAuth: true,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "linear",
    label: "Linear",
    icon: "linear",
    authorizeUrl: "https://linear.app/oauth/authorize",
    tokenUrl: "https://api.linear.app/oauth/token",
    apiBaseUrl: "https://api.linear.app/graphql",
    docsUrl: "https://linear.app/settings/api/applications/new",
    scopes: ["read", "write"],
    usePkce: true,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "github",
    label: "GitHub",
    icon: "github",
    authorizeUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
    apiBaseUrl: "https://api.github.com",
    docsUrl: "https://github.com/settings/developers",
    scopes: ["repo", "read:user"],
    usePkce: false,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "slack",
    label: "Slack",
    authorizeUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
    apiBaseUrl: "https://slack.com/api",
    docsUrl: "https://api.slack.com/apps",
    scopes: ["channels:read", "chat:write"],
    usePkce: false,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "google-drive",
    label: "Google Drive",
    icon: "googledrive",
    authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    apiBaseUrl: "https://www.googleapis.com/drive/v3",
    docsUrl: "https://console.cloud.google.com/apis/credentials",
    scopes: ["https://www.googleapis.com/auth/drive.readonly"],
    usePkce: true,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "gmail",
    label: "Gmail",
    icon: "gmail",
    authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    apiBaseUrl: "https://gmail.googleapis.com/gmail/v1",
    docsUrl: "https://console.cloud.google.com/apis/credentials",
    scopes: ["https://www.googleapis.com/auth/gmail.readonly"],
    usePkce: true,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "google-calendar",
    label: "Google Calendar",
    icon: "googlecalendar",
    authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    apiBaseUrl: "https://www.googleapis.com/calendar/v3",
    docsUrl: "https://console.cloud.google.com/apis/credentials",
    scopes: ["https://www.googleapis.com/auth/calendar.readonly"],
    usePkce: true,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "atlassian",
    label: "Atlassian",
    icon: "atlassian",
    authorizeUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    apiBaseUrl: "https://api.atlassian.com",
    docsUrl: "https://developer.atlassian.com/console/myapps/",
    scopes: ["read:jira-work", "offline_access"],
    usePkce: true,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "figma",
    label: "Figma",
    icon: "figma",
    authorizeUrl: "https://www.figma.com/oauth",
    tokenUrl: "https://api.figma.com/v1/oauth/token",
    apiBaseUrl: "https://api.figma.com/v1",
    docsUrl: "https://www.figma.com/developers/apps",
    scopes: ["file_read"],
    usePkce: false,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "box",
    label: "Box",
    icon: "box",
    authorizeUrl: "https://account.box.com/api/oauth2/authorize",
    tokenUrl: "https://api.box.com/oauth2/token",
    apiBaseUrl: "https://api.box.com/2.0",
    docsUrl: "https://app.box.com/developers/console",
    scopes: [],
    usePkce: false,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "hubspot",
    label: "HubSpot",
    icon: "hubspot",
    authorizeUrl: "https://app.hubspot.com/oauth/authorize",
    tokenUrl: "https://api.hubapi.com/oauth/v1/token",
    apiBaseUrl: "https://api.hubapi.com",
    docsUrl: "https://developers.hubspot.com/docs/api/working-with-oauth",
    scopes: ["crm.objects.contacts.read"],
    usePkce: false,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "asana",
    label: "Asana",
    icon: "asana",
    authorizeUrl: "https://app.asana.com/-/oauth_authorize",
    tokenUrl: "https://app.asana.com/-/oauth_token",
    apiBaseUrl: "https://app.asana.com/api/1.0",
    docsUrl: "https://app.asana.com/0/my-apps",
    scopes: ["default"],
    usePkce: true,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "intercom",
    label: "Intercom",
    icon: "intercom",
    authorizeUrl: "https://app.intercom.com/oauth",
    tokenUrl: "https://api.intercom.io/auth/eagle/token",
    apiBaseUrl: "https://api.intercom.io",
    docsUrl: "https://developers.intercom.com/building-apps/docs/setting-up-oauth",
    scopes: [],
    usePkce: false,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "monday",
    label: "monday.com",
    authorizeUrl: "https://auth.monday.com/oauth2/authorize",
    tokenUrl: "https://auth.monday.com/oauth2/token",
    apiBaseUrl: "https://api.monday.com/v2",
    docsUrl: "https://monday.com/developers/apps",
    scopes: ["boards:read"],
    usePkce: false,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "xero",
    label: "Xero",
    icon: "xero",
    authorizeUrl: "https://login.xero.com/identity/connect/authorize",
    tokenUrl: "https://identity.xero.com/connect/token",
    apiBaseUrl: "https://api.xero.com/api.xro/2.0",
    docsUrl: "https://developer.xero.com/app/manage",
    scopes: ["offline_access", "accounting.transactions.read"],
    usePkce: true,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
  {
    provider: "microsoft-365",
    label: "Microsoft 365",
    authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    apiBaseUrl: "https://graph.microsoft.com/v1.0",
    docsUrl: "https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade",
    scopes: ["offline_access", "User.Read", "Files.Read"],
    usePkce: true,
    useBasicAuth: false,
    redirectUri: LOOPBACK_REDIRECT,
  },
];
